export const sidebarLinks = [
  {
    imgURL: "/icons/home.svg",
    route: "/dashboard",
    label: "Home",
  },
  {
    imgURL: "/icons/basketballIcon.svg",
    route: "/dashboard/start-game",
    label: "Start Game",
  },
  {
    imgURL: "/icons/previous.svg",
    route: "/dashboard/recorded-games",
    label: "Recorded Games",
  },
  {
    imgURL: "/icons/player.svg",
    route: "/dashboard/players-stats",
    label: "Players Statistics",
  },
];
export const fieldGoals: string[] = ["1-Point", "2-Points", "3-Points"];
export const rebounds: string[] = ["D-Rebound", "O-Rebound"];
export const assists: string[] = ["Assist"];
export const steals: string[] = ["Steal"];
export const blocks: string[] = ["Block"];

export const nbaTeams: team[] = [
  {
    name: "Atlanta Hawks",
    coachName: "Quin Snyder",
    startingFive: [
      "Trae Young",
      "Dejounte Murray",
      "De'Andre Hunter",
      "John Collins",
      "Clint Capela",
    ],
  },
  {
    name: "Boston Celtics",
    coachName: "Joe Mazzulla",
    startingFive: [
      "Jayson Tatum",
      "Jaylen Brown",
      "Marcus Smart",
      "Al Horford",
      "Robert Williams III",
    ],
  },
  {
    name: "Brooklyn Nets",
    coachName: "Jacque Vaughn",
    startingFive: [
      "Mikal Bridges",
      "Spencer Dinwiddie",
      "Cam Thomas",
      "Nic Claxton",
      "Royce O'Neale",
    ],
  },
  {
    name: "Charlotte Hornets",
    coachName: "Steve Clifford",
    startingFive: [
      "LaMelo Ball",
      "Terry Rozier",
      "Kelly Oubre Jr.",
      "P.J. Washington",
      "Mason Plumlee",
    ],
  },
  {
    name: "Chicago Bulls",
    coachName: "Billy Donovan",
    startingFive: [
      "DeMar DeRozan",
      "Zach LaVine",
      "Patrick Williams",
      "Nikola Vučević",
      "Andre Drummond",
    ],
  },
  {
    name: "Cleveland Cavaliers",
    coachName: "J.B. Bickerstaff",
    startingFive: [
      "Donovan Mitchell",
      "Darius Garland",
      "Caris LeVert",
      "Evan Mobley",
      "Jarrett Allen",
    ],
  },
  {
    name: "Dallas Mavericks",
    coachName: "Jason Kidd",
    startingFive: [
      "Luka Dončić",
      "Kyrie Irving",
      "Josh Green",
      "Maxi Kleber",
      "Dwight Powell",
    ],
  },
  {
    name: "Denver Nuggets",
    coachName: "Michael Malone",
    startingFive: [
      "Nikola Jokić",
      "Jamal Murray",
      "Michael Porter Jr.",
      "Aaron Gordon",
      "Nicolás Brussino",
    ],
  },
  {
    name: "Detroit Pistons",
    coachName: "Monty Williams",
    startingFive: [
      "Cade Cunningham",
      "Jaden Ivey",
      "Bojan Bogdanović",
      "Isaiah Stewart",
      "James Wiseman",
    ],
  },
  {
    name: "Golden State Warriors",
    coachName: "Steve Kerr",
    startingFive: [
      "Stephen Curry",
      "Klay Thompson",
      "Andrew Wiggins",
      "Draymond Green",
      "Kevon Looney",
    ],
  },
  {
    name: "Houston Rockets",
    coachName: "Ime Udoka",
    startingFive: [
      "Jalen Green",
      "Kevin Porter Jr.",
      "Jabari Smith Jr.",
      "Alperen Şengün",
      "Bruno Fernando",
    ],
  },
  {
    name: "Indiana Pacers",
    coachName: "Rick Carlisle",
    startingFive: [
      "Tyrese Haliburton",
      "Bennedict Mathurin",
      "Buddy Hield",
      "Oshae Brissett",
      "Myles Turner",
    ],
  },
  {
    name: "Los Angeles Clippers",
    coachName: "Tyronn Lue",
    startingFive: [
      "Kawhi Leonard",
      "Paul George",
      "Norman Powell",
      "Terance Mann",
      "Ivica Zubac",
    ],
  },
  {
    name: "Los Angeles Lakers",
    coachName: "Darvin Ham",
    startingFive: [
      "LeBron James",
      "D'Angelo Russell",
      "Austin Reaves",
      "Rui Hachimura",
      "Anthony Davis",
    ],
  },
  {
    name: "Memphis Grizzlies",
    coachName: "Taylor Jenkins",
    startingFive: [
      "Ja Morant",
      "Desmond Bane",
      "Dillon Brooks",
      "Jaren Jackson Jr.",
      "Steven Adams",
    ],
  },
  {
    name: "Miami Heat",
    coachName: "Erik Spoelstra",
    startingFive: [
      "Jimmy Butler",
      "Bam Adebayo",
      "Caleb Martin",
      "Gabe Vincent",
      "Kevin Love",
    ],
  },
  {
    name: "Milwaukee Bucks",
    coachName: "Mike Budenholzer",
    startingFive: [
      "Giannis Antetokounmpo",
      "Jrue Holiday",
      "Khris Middleton",
      "Bobby Portis",
      "Brook Lopez",
    ],
  },
  {
    name: "Minnesota Timberwolves",
    coachName: "Chris Finch",
    startingFive: [
      "Anthony Edwards",
      "Rudy Gobert",
      "Karl-Anthony Towns",
      "Jaden McDaniels",
      "Austin Rivers",
    ],
  },
  {
    name: "New Orleans Pelicans",
    coachName: "Willie Green",
    startingFive: [
      "Zion Williamson",
      "Brandon Ingram",
      "CJ McCollum",
      "Herbert Jones",
      "Jonas Valančiūnas",
    ],
  },
  {
    name: "New York Knicks",
    coachName: "Tom Thibodeau",
    startingFive: [
      "Jalen Brunson",
      "RJ Barrett",
      "Quentin Grimes",
      "Julius Randle",
      "Mitchell Robinson",
    ],
  },
  {
    name: "Oklahoma City Thunder",
    coachName: "Mark Daigneault",
    startingFive: [
      "Shai Gilgeous-Alexander",
      "Luguentz Dort",
      "Jalen Williams",
      "Josh Giddey",
      "Chet Holmgren",
    ],
  },
  {
    name: "Orlando Magic",
    coachName: "Jamahl Mosley",
    startingFive: [
      "Paolo Banchero",
      "Franz Wagner",
      "Jalen Suggs",
      "Bol Bol",
      "Wendell Carter Jr.",
    ],
  },
  {
    name: "Philadelphia 76ers",
    coachName: "Doc Rivers",
    startingFive: [
      "James Harden",
      "Tyrese Maxey",
      "Tobias Harris",
      "P.J. Tucker",
      "Joel Embiid",
    ],
  },
  {
    name: "Phoenix Suns",
    coachName: "Frank Vogel",
    startingFive: [
      "Devin Booker",
      "Bradley Beal",
      "Kevin Durant",
      "Deandre Ayton",
      "Josh Okogie",
    ],
  },
  {
    name: "Portland Trail Blazers",
    coachName: "Chauncey Billups",
    startingFive: [
      "Damian Lillard",
      "Anfernee Simons",
      "Jerami Grant",
      "Jusuf Nurkić",
      "Drew Eubanks",
    ],
  },
  {
    name: "Sacramento Kings",
    coachName: "Mike Brown",
    startingFive: [
      "De'Aaron Fox",
      "Kevin Huerter",
      "Keegan Murray",
      "Domantas Sabonis",
      "Alex Len",
    ],
  },
  {
    name: "San Antonio Spurs",
    coachName: "Gregg Popovich",
    startingFive: [
      "Victor Wembanyama",
      "Scoot Henderson",
      "Devin Vassell",
      "Keldon Johnson",
      "Zach Collins",
    ],
  },
  {
    name: "Toronto Raptors",
    coachName: "Darko Rajaković",
    startingFive: [
      "Fred VanVleet",
      "Scottie Barnes",
      "OG Anunoby",
      "Pascal Siakam",
      "Jakob Poeltl",
    ],
  },
  {
    name: "Utah Jazz",
    coachName: "Will Hardy",
    startingFive: [
      "Lauri Markkanen",
      "Collin Sexton",
      "Kris Dunn",
      "Jarred Vanderbilt",
      "Walker Kessler",
    ],
  },
  {
    name: "Washington Wizards",
    coachName: "Wes Unseld Jr.",
    startingFive: [
      "Kyle Kuzma",
      "Corey Kispert",
      "Kristaps Porziņģis",
      "Daniel Gafford",
      "Delon Wright",
    ],
  },
];

export const teamImgs = [
  {
    name: "Boston Celtics",
    img: "/teams/Boston Celtics.svg",
  },
  {
    name: "Brooklyn Nets",
    img: "/teams/Brooklyn Nets.svg",
  },
  {
    name: "New York Knicks",
    img: "/teams/New York Knicks.svg",
  },
  {
    name: "Philadelphia 76ers",
    img: "/teams/Philadelphia 76ers.svg",
  },
  {
    name: "Toronto Raptors",
    img: "/teams/Toronto Raptors.svg",
  },
  {
    name: "Chicago Bulls",
    img: "/teams/Chicago Bulls.svg",
  },
  {
    name: "Detroit Pistons",
    img: "/teams/Detroit Pistons.svg",
  },
  {
    name: "Indiana Pacers",
    img: "/teams/Indiana Pacers.svg",
  },
  {
    name: "Milwaukee Bucks",
    img: "/teams/Milwaukee Bucks.svg",
  },
  {
    name: "Atlanta Hawks",
    img: "/teams/Atlanta Hawks.svg",
  },
  {
    name: "Charlotte Hornets",
    img: "/teams/Charlotte Hornets.svg",
  },
  {
    name: "Miami Heat",
    img: "/teams/Miami Heat.svg",
  },
  {
    name: "Orlando Magic",
    img: "/teams/Orlando Magic.svg",
  },
  {
    name: "Washington Wizards",
    img: "/teams/Washington Wizards.svg",
  },
  {
    name: "Denver Nuggets",
    img: "/teams/Denver Nuggets.svg",
  },
  {
    name: "Minnesota Timberwolves",
    img: "/teams/Minnesota Timberwolves.svg",
  },
  {
    name: "Oklahoma City Thunder",
    img: "/teams/Oklahoma City Thunder.svg",
  },
  {
    name: "Portland Trail Blazers",
    img: "/teams/Portland Trail Blazers.svg",
  },
  {
    name: "Utah Jazz",
    img: "/teams/Utah Jazz.svg",
  },
  {
    name: "Golden State Warriors",
    img: "/teams/Golden State Warriors.svg",
  },
  {
    name: "Los Angeles Clippers",
    img: "/teams/Los Angeles Clippers.svg",
  },
  {
    name: "Los Angeles Lakers",
    img: "/teams/Los Angeles Lakers.svg",
  },
  {
    name: "Phoenix Suns",
    img: "/teams/Phoenix Suns.svg",
  },
  {
    name: "Sacramento Kings",
    img: "/teams/Sacramento Kings.svg",
  },
  {
    name: "Dallas Mavericks",
    img: "/teams/Dallas Mavericks.svg",
  },
  {
    name: "Houston Rockets",
    img: "/teams/Houston Rockets.svg",
  },
  {
    name: "Memphis Grizzlies",
    img: "/teams/Memphis Grizzlies.svg",
  },
  {
    name: "New Orleans Pelicans",
    img: "/teams/New Orleans Pelicans.svg",
  },
  {
    name: "San Antonio Spurs",
    img: "/teams/San Antonio Spurs.svg",
  },
];

export const playerIMgs = [
  {
    name: "Trae Young",
    img: "/players/Trae Young.webp",
    height: "6'1\"",
    weight: "164 lbs",
    jersey: 11,
  },
  {
    name: "Nicolás Brussino",
    img: "",
    height: "6 ft 7 in",
    weight: "195 lbs",
    jersey: "9",
  },
  {
    name: "Cade Cunningham",
    img: "/players/Cade Cunningham.avif",
    height: "6 ft 6 in",
    weight: "220 lbs",
    jersey: "2",
  },

  {
    name: "Dejounte Murray",
    img: "/players/Dejounte Murray.webp",
    height: "6'4\"",
    weight: "180 lbs",
    jersey: 5,
  },
  {
    name: "De'Andre Hunter",
    img: "/players/De'Andre Hunter.avif",
    height: "6'8\"",
    weight: "225 lbs",
    jersey: 12,
  },
  {
    name: "Jaden Ivey",
    img: "/players/Jaden Ivey.webp",
    height: "6 ft 4 in",
    weight: "195 lbs",
    jersey: "23",
  },

  {
    name: "John Collins",
    img: "/players/John Collins.avif",
    height: "6'9\"",
    weight: "226 lbs",
    jersey: 20,
  },
  {
    name: "Clint Capela",
    img: "/players/Clint Capela.webp",
    height: "6'10\"",
    weight: "256 lbs",
    jersey: 15,
  },
  {
    name: "Josh Green",
    img: "/players/Josh Green.webp",
    height: "6 ft 7 in",
    weight: "200 lbs",
    jersey: "8",
  },
  {
    name: "Maxi Kleber",
    img: "/players/Maxi Kleber.avif",
    height: "6 ft 10 in",
    weight: "240 lbs",
    jersey: "42",
  },
  {
    name: "Dwight Powell",
    img: "/players/Dwight Powell.avif",
    height: "6 ft 10 in",
    weight: "240 lbs",
    jersey: "7",
  },
  {
    name: "James Wiseman",
    img: "/players/James Wiseman.webp",
    height: "7 ft 0 in",
    weight: "240 lbs",
    jersey: "21",
  },

  {
    name: "Jayson Tatum",
    img: "/players/Jayson Tatum.avif",
    height: "6'8\"",
    weight: "210 lbs",
    jersey: 0,
  },
  {
    name: "Jaylen Brown",
    img: "/players/Jaylen Brown.avif",
    height: "6'6\"",
    weight: "223 lbs",
    jersey: 7,
  },
  {
    name: "D'Angelo Russell",
    img: "/players/D'Angelo Russell.webp",
    height: "6 ft 4 in",
    weight: "193 lbs",
    jersey: "1",
  },
  {
    name: "Austin Reaves",
    img: "/players/Austin Reaves.avif",
    height: "6 ft 5 in",
    weight: "206 lbs",
    jersey: "15",
  },
  {
    name: "Rui Hachimura",
    img: "/players/Rui Hachimura.avif",
    height: "6 ft 8 in",
    weight: "230 lbs",
    jersey: "28",
  },

  {
    name: "Marcus Smart",
    img: "/players/Marcus Smart.avif",
    height: "6'4\"",
    weight: "220 lbs",
    jersey: 36,
  },
  {
    name: "Bojan Bogdanović",
    img: "/players/Bojan Bogdanović.avif",
    height: "6 ft 7 in",
    weight: "226 lbs",
    jersey: "44",
  },
  {
    name: "Paul George",
    img: "/players/Paul George.webp",
    height: "6 ft 8 in",
    weight: "220 lbs",
    jersey: "13",
  },

  {
    name: "Al Horford",
    img: "/players/Al Horford.avif",
    height: "6'9\"",
    weight: "240 lbs",
    jersey: 42,
  },
  {
    name: "Robert Williams III",
    img: "/players/Robert Williams III.png",
    height: "6'9\"",
    weight: "237 lbs",
    jersey: 44,
  },
  {
    name: "Mikal Bridges",
    img: "/players/Mikal Bridges.avif",
    height: "6'6\"",
    weight: "209 lbs",
    jersey: 1,
  },
  {
    name: "Norman Powell",
    img: "/players/Norman Powell.webp",
    height: "6 ft 3 in",
    weight: "215 lbs",
    jersey: "24",
  },
  {
    name: "Ja Morant",
    img: "/players/Ja Morant.avif",
    height: "6 ft 2 in",
    weight: "174 lbs",
    jersey: "12",
  },
  {
    name: "Desmond Bane",
    img: "/players/Desmond Bane.avif",
    height: "6 ft 5 in",
    weight: "215 lbs",
    jersey: "22",
  },
  {
    name: "Dillon Brooks",
    img: "/players/Dillon Brooks.webp",
    height: "6 ft 7 in",
    weight: "225 lbs",
    jersey: "24",
  },
  {
    name: "Jimmy Butler",
    img: "/players/Jimmy Butler.webp",
    height: "6 ft 7 in",
    weight: "230 lbs",
    jersey: "22",
  },
  {
    name: "Bam Adebayo",
    img: "/players/Bam Adebayo.webp",
    height: "6 ft 9 in",
    weight: "255 lbs",
    jersey: "13",
  },
  {
    name: "Caleb Martin",
    img: "/players/Caleb Martin.webp",
    height: "6 ft 5 in",
    weight: "205 lbs",
    jersey: "16",
  },
  {
    name: "Gabe Vincent",
    img: "/players/Gabe Vincent.webp",
    height: "6 ft 3 in",
    weight: "200 lbs",
    jersey: "2",
  },
  {
    name: "Kevin Love",
    img: "/players/Kevin Love.webp",
    height: "6 ft 8 in",
    weight: "251 lbs",
    jersey: "42",
  },

  {
    name: "Jaren Jackson Jr.",
    img: "/players/Jaren Jackson Jr.avif",
    height: "6 ft 10 in",
    weight: "242 lbs",
    jersey: "13",
  },
  {
    name: "Steven Adams",
    img: "/players/Steven Adams.png",
    height: "6 ft 11 in",
    weight: "265 lbs",
    jersey: "4",
  },

  {
    name: "Terance Mann",
    img: "/players/Terance Mann.png",
    height: "6 ft 5 in",
    weight: "215 lbs",
    jersey: "14",
  },
  {
    name: "Ivica Zubac",
    img: "/players/Ivica Zubac.webp",
    height: "7 ft 0 in",
    weight: "240 lbs",
    jersey: "40",
  },
  {
    name: "Draymond Green",
    img: "/players/Draymond Green.avif",
    height: "6 ft 6 in",
    weight: "230 lbs",
    jersey: "23",
  },
  {
    name: "Bennedict Mathurin",
    img: "/players/Bennedict Mathurin.webp",
    height: "6 ft 6 in",
    weight: "210 lbs",
    jersey: "00",
  },

  {
    name: "Tyrese Haliburton",
    img: "/players/Tyrese Haliburton.webp",
    height: "6 ft 5 in",
    weight: "185 lbs",
    jersey: "0",
  },
  {
    name: "Kawhi Leonard",
    img: "/players/Kawhi Leonard.png",
    height: "6 ft 7 in",
    weight: "225 lbs",
    jersey: "2",
  },

  {
    name: "Spencer Dinwiddie",
    img: "/players/Spencer Dinwiddie.avif",
    height: "6'5\"",
    weight: "215 lbs",
    jersey: 26,
  },
  {
    name: "Cam Thomas",
    img: "/players/Cam Thomas.avif",
    height: "6'3\"",
    weight: "210 lbs",
    jersey: 24,
  },
  {
    name: "Oshae Brissett",
    img: "/players/Oshae Brissett.avif",
    height: "6 ft 7 in",
    weight: "210 lbs",
    jersey: "12",
  },
  {
    name: "Myles Turner",
    img: "/players/Myles Turner.webp",
    height: "6 ft 11 in",
    weight: "250 lbs",
    jersey: "33",
  },

  {
    name: "Buddy Hield",
    img: "/players/Buddy Hield.webp",
    height: "6 ft 4 in",
    weight: "220 lbs",
    jersey: "24",
  },

  {
    name: "Nic Claxton",
    img: "/players/Nic Claxton.webp",
    height: "6'11\"",
    weight: "215 lbs",
    jersey: 33,
  },
  {
    name: "Jalen Green",
    img: "/players/Jalen Green.webp",
    height: "6 ft 4 in",
    weight: "186 lbs",
    jersey: "4",
  },
  {
    name: "Kevin Porter Jr.",
    img: "/players/Kevin Porter Jr.png",
    height: "6 ft 4 in",
    weight: "203 lbs",
    jersey: "3",
  },

  {
    name: "Royce O'Neale",
    img: "/players/Royce O'Neale.webp",
    height: "6'5\"",
    weight: "226 lbs",
    jersey: 0,
  },
  {
    name: "Alperen Şengün",
    img: "/players/Alperen Şengün.webp",
    height: "6 ft 9 in",
    weight: "243 lbs",
    jersey: "28",
  },
  {
    name: "Bruno Fernando",
    img: "/players/Bruno Fernando.webp",
    height: "6 ft 10 in",
    weight: "240 lbs",
    jersey: "20",
  },

  {
    name: "Jabari Smith Jr.",
    img: "/players/Jabari Smith Jr.webp",
    height: "6 ft 10 in",
    weight: "220 lbs",
    jersey: "1",
  },

  {
    name: "Kevon Looney",
    img: "/players/Kevon Looney.avif",
    height: "6 ft 9 in",
    weight: "222 lbs",
    jersey: "5",
  },

  {
    name: "Andrew Wiggins",
    img: "/players/Andrew Wiggins.avif",
    height: "6 ft 7 in",
    weight: "197 lbs",
    jersey: "22",
  },

  {
    name: "LaMelo Ball",
    img: "/players/LaMelo Ball.webp",
    height: "6'7\"",
    weight: "180 lbs",
    jersey: 1,
  },
  {
    name: "Terry Rozier",
    img: "/players/Terry Rozier.webp",
    height: "6'1\"",
    weight: "190 lbs",
    jersey: 3,
  },
  {
    name: "Kelly Oubre Jr.",
    img: "/players/Kelly Oubre Jr.webp",
    height: "6'7\"",
    weight: "203 lbs",
    jersey: 12,
  },
  {
    name: "Isaiah Stewart",
    img: "/players/Isaiah Stewart.avif",
    height: "6 ft 8 in",
    weight: "250 lbs",
    jersey: "28",
  },

  {
    name: "P.J. Washington",
    img: "/players/P.J. Washington.avif",
    height: "6'7\"",
    weight: "230 lbs",
    jersey: 25,
  },
  {
    name: "Mason Plumlee",
    img: "/players/Mason Plumlee.avif",
    height: "6'11\"",
    weight: "254 lbs",
    jersey: 24,
  },
  {
    name: "DeMar DeRozan",
    img: "/players/DeMar DeRozan.avif",
    height: "6'6\"",
    weight: "220 lbs",
    jersey: 11,
  },
  {
    name: "Zach LaVine",
    img: "/players/Zach LaVine.webp",
    height: "6'5\"",
    weight: "200 lbs",
    jersey: 8,
  },
  {
    name: "Patrick Williams",
    img: "/players/Patrick Williams.webp",
    height: "6'7\"",
    weight: "215 lbs",
    jersey: 44,
  },
  {
    name: "Nikola Vučević",
    img: "/players/Nikola Vučević.webp",
    height: "6'10\"",
    weight: "260 lbs",
    jersey: 9,
  },
  {
    name: "Andre Drummond",
    img: "/players/Andre Drummond.avif",
    height: "6'10\"",
    weight: "279 lbs",
    jersey: 3,
  },
  {
    name: "Donovan Mitchell",
    img: "/players/Donovan Mitchell.avif",
    height: "6'1\"",
    weight: "215 lbs",
    jersey: 45,
  },
  {
    name: "Darius Garland",
    img: "/players/Darius Garland.avif",
    height: "6'1\"",
    weight: "192 lbs",
    jersey: 10,
  },
  {
    name: "Caris LeVert",
    img: "/players/Caris LeVert.avif",
    height: "6'6\"",
    weight: "205 lbs",
    jersey: 3,
  },
  {
    name: "Evan Mobley",
    img: "/players/Evan Mobley.avif",
    height: "7'0\"",
    weight: "215 lbs",
    jersey: 4,
  },
  {
    name: "Jarrett Allen",
    img: "/players/Jarrett Allen.avif",
    height: "6'9\"",
    weight: "243 lbs",
    jersey: 31,
  },
  {
    name: "Luka Dončić",
    img: "/players/Luka Dončić.avif",
    height: "6'7\"",
    weight: "230 lbs",
    jersey: 77,
  },
  {
    name: "Kyrie Irving",
    img: "/players/Kyrie Irving.webp",
    height: "6'2\"",
    weight: "195 lbs",
    jersey: 11,
  },
  {
    name: "Nikola Jokić",
    img: "/players/Nikola Jokić.avif",
    height: "6'11\"",
    weight: "284 lbs",
    jersey: 15,
  },
  {
    name: "Jamal Murray",
    img: "/players/Jamal Murray.avif",
    height: "6'4\"",
    weight: "215 lbs",
    jersey: 27,
  },
  {
    name: "Michael Porter Jr.",
    img: "/players/Michael Porter Jr.avif",
    height: "6 ft 10 in",
    weight: "218 lbs",
    jersey: "1",
  },
  {
    name: "Aaron Gordon",
    img: "/players/Aaron Gordon.avif",
    height: "6'8\"",
    weight: "235 lbs",
    jersey: 50,
  },
  {
    name: "Stephen Curry",
    img: "/players/Stephen Curry.avif",
    height: "6'2\"",
    weight: "185 lbs",
    jersey: 30,
  },
  {
    name: "Klay Thompson",
    img: "/players/Klay Thompson.avif",
    height: "6'6\"",
    weight: "215 lbs",
    jersey: 11,
  },
  {
    name: "LeBron James",
    img: "/players/LeBron James.avif",
    height: "6'9\"",
    weight: "250 lbs",
    jersey: 6,
  },
  {
    name: "Anthony Davis",
    img: "/players/Anthony Davis.avif",
    height: "6'10\"",
    weight: "253 lbs",
    jersey: 3,
  },
  {
    name: "Giannis Antetokounmpo",
    img: "/players/Giannis Antetokounmpo.webp",
    height: "6'11\"",
    weight: "243 lbs",
    jersey: 34,
  },
  {
    name: "Jrue Holiday",
    img: "/players/Jrue Holiday.avif",
    height: "6 ft 5 in",
    weight: "205 lbs",
    jersey: "21",
  },
  {
    name: "Khris Middleton",
    img: "/players/Khris Middleton.webp",
    height: "6 ft 7 in",
    weight: "222 lbs",
    jersey: "22",
  },
  {
    name: "Bobby Portis",
    img: "/players/Bobby Portis.avif",
    height: "6 ft 10 in",
    weight: "250 lbs",
    jersey: "9",
  },
  {
    name: "Brook Lopez",
    img: "/players/Brook Lopez.avif",
    height: "7 ft 0 in",
    weight: "282 lbs",
    jersey: "11",
  },
  {
    name: "Anthony Edwards",
    img: "/players/Anthony Edwards.avif",
    height: "6 ft 4 in",
    weight: "225 lbs",
    jersey: "1",
  },
  {
    name: "Rudy Gobert",
    img: "/players/Rudy Gobert.avif",
    height: "7 ft 1 in",
    weight: "258 lbs",
    jersey: "27",
  },
  {
    name: "Karl-Anthony Towns",
    img: "/players/Karl-Anthony Towns.webp",
    height: "6 ft 11 in",
    weight: "248 lbs",
    jersey: "32",
  },
  {
    name: "Jaden McDaniels",
    img: "/players/Jaden McDaniels.avif",
    height: "6 ft 9 in",
    weight: "185 lbs",
    jersey: "3",
  },
  {
    name: "Austin Rivers",
    img: "/players/Austin Rivers.avif",
    height: "6 ft 4 in",
    weight: "200 lbs",
    jersey: "25",
  },
  {
    name: "Zion Williamson",
    img: "/players/Zion Williamson.avif",
    height: "6 ft 6 in",
    weight: "284 lbs",
    jersey: "1",
  },
  {
    name: "Brandon Ingram",
    img: "/players/Brandon Ingram.avif",
    height: "6 ft 8 in",
    weight: "190 lbs",
    jersey: "14",
  },
  {
    name: "CJ McCollum",
    img: "/players/CJ McCollum.webp",
    height: "6 ft 3 in",
    weight: "190 lbs",
    jersey: "3",
  },
  {
    name: "Herbert Jones",
    img: "/players/Herbert Jones.webp",
    height: "6 ft 7 in",
    weight: "206 lbs",
    jersey: "5",
  },
  {
    name: "Jonas Valančiūnas",
    img: "/players/Jonas Valančiūnas.webp",
    height: "6 ft 11 in",
    weight: "265 lbs",
    jersey: "17",
  },
  {
    name: "Jalen Brunson",
    img: "/players/Jalen Brunson.webp",
    height: "6 ft 1 in",
    weight: "190 lbs",
    jersey: "11",
  },
  {
    name: "RJ Barrett",
    img: "/players/RJ Barrett.webp",
    height: "6 ft 6 in",
    weight: "214 lbs",
    jersey: "9",
  },
  {
    name: "Quentin Grimes",
    img: "/players/Quentin Grimes.avif",
    height: "6 ft 5 in",
    weight: "210 lbs",
    jersey: "6",
  },
  {
    name: "Julius Randle",
    img: "/players/Julius Randle.avif",
    height: "6 ft 8 in",
    weight: "250 lbs",
    jersey: "30",
  },
  {
    name: "Mitchell Robinson",
    img: "/players/Mitchell Robinson.webp",
    height: "7 ft 0 in",
    weight: "240 lbs",
    jersey: "23",
  },
  {
    name: "Shai Gilgeous-Alexander",
    img: "/players/Shai Gilgeous-Alexander.webp",
    height: "6 ft 6 in",
    weight: "195 lbs",
    jersey: "2",
  },
  {
    name: "Luguentz Dort",
    img: "/players/Luguentz Dort.webp",
    height: "6 ft 4 in",
    weight: "220 lbs",
    jersey: "5",
  },
  {
    name: "Jalen Williams",
    img: "/players/Jalen Williams.webp",
    height: "6 ft 6 in",
    weight: "195 lbs",
    jersey: "8",
  },
  {
    name: "Josh Giddey",
    img: "/players/Josh Giddey.webp",
    height: "6 ft 8 in",
    weight: "210 lbs",
    jersey: "3",
  },
  {
    name: "Chet Holmgren",
    img: "/players/Chet Holmgren.png",
    height: "7 ft 1 in",
    weight: "208 lbs",
    jersey: "7",
  },
  {
    name: "Paolo Banchero",
    img: "/players/Paolo Banchero.avif",
    height: "6 ft 10 in",
    weight: "250 lbs",
    jersey: "5",
  },
  {
    name: "Franz Wagner",
    img: "/players/Franz Wagner.avif",
    height: "6 ft 9 in",
    weight: "220 lbs",
    jersey: "22",
  },
  {
    name: "Jalen Suggs",
    img: "/players/Jalen Suggs.avif",
    height: "6 ft 4 in",
    weight: "205 lbs",
    jersey: "4",
  },
  {
    name: "Bol Bol",
    img: "/players/Bol Bol.avif",
    height: "7 ft 2 in",
    weight: "220 lbs",
    jersey: "10",
  },
  {
    name: "Wendell Carter Jr.",
    img: "/players/Wendell Carter Jr.avif",
    height: "6 ft 10 in",
    weight: "270 lbs",
    jersey: "34",
  },
  {
    name: "James Harden",
    img: "/players/James Harden.png",
    height: "6 ft 5 in",
    weight: "220 lbs",
    jersey: "1",
  },
  {
    name: "Tyrese Maxey",
    img: "/players/Tyrese Maxey.avif",
    height: "6 ft 2 in",
    weight: "200 lbs",
    jersey: "0",
  },
  {
    name: "Tobias Harris",
    img: "/players/Tobias Harris.webp",
    height: "6 ft 8 in",
    weight: "226 lbs",
    jersey: "12",
  },
  {
    name: "P.J. Tucker",
    img: "/players/P.J. Tucker.avif",
    height: "6 ft 5 in",
    weight: "245 lbs",
    jersey: "17",
  },
  {
    name: "Joel Embiid",
    img: "/players/Joel Embiid.webp",
    height: "7 ft 0 in",
    weight: "280 lbs",
    jersey: "21",
  },
  {
    name: "Devin Booker",
    img: "/players/Devin Booker.avif",
    height: "6 ft 5 in",
    weight: "206 lbs",
    jersey: "1",
  },
  {
    name: "Bradley Beal",
    img: "/players/Bradley Beal.avif",
    height: "6 ft 4 in",
    weight: "207 lbs",
    jersey: "3",
  },
  {
    name: "Kevin Durant",
    img: "/players/Kevin Durant.avif",
    height: "6 ft 10 in",
    weight: "240 lbs",
    jersey: "35",
  },
  {
    name: "Deandre Ayton",
    img: "/players/Deandre Ayton.webp",
    height: "7 ft 0 in",
    weight: "250 lbs",
    jersey: "22",
  },
  {
    name: "Josh Okogie",
    img: "/players/Josh Okogie.avif",
    height: "6 ft 4 in",
    weight: "213 lbs",
    jersey: "20",
  },
  {
    name: "Damian Lillard",
    img: "/players/Damian Lillard.webp",
    height: "6 ft 2 in",
    weight: "195 lbs",
    jersey: "0",
  },
  {
    name: "Anfernee Simons",
    img: "/players/Anfernee Simons.webp",
    height: "6 ft 3 in",
    weight: "181 lbs",
    jersey: "1",
  },
  {
    name: "Jerami Grant",
    img: "/players/Jerami Grant.webp",
    height: "6 ft 8 in",
    weight: "210 lbs",
    jersey: "9",
  },
  {
    name: "Jusuf Nurkić",
    img: "/players/Jusuf Nurkić.webp",
    height: "6 ft 11 in",
    weight: "290 lbs",
    jersey: "27",
  },
  {
    name: "Drew Eubanks",
    img: "/players/Drew Eubanks.avif",
    height: "6 ft 9 in",
    weight: "245 lbs",
    jersey: "24",
  },
  {
    name: "De'Aaron Fox",
    img: "/players/De'Aaron Fox.avif",
    height: "6 ft 3 in",
    weight: "185 lbs",
    jersey: "5",
  },
  {
    name: "Kevin Huerter",
    img: "/players/Kevin Huerter.avif",
    height: "6 ft 7 in",
    weight: "190 lbs",
    jersey: "9",
  },
  {
    name: "Keegan Murray",
    img: "/players/Keegan Murray.avif",
    height: "6 ft 8 in",
    weight: "225 lbs",
    jersey: "13",
  },
  {
    name: "Domantas Sabonis",
    img: "/players/Domantas Sabonis.avif",
    height: "6 ft 11 in",
    weight: "240 lbs",
    jersey: "10",
  },
  {
    name: "Alex Len",
    img: "/players/Alex Len.avif",
    height: "7 ft 0 in",
    weight: "250 lbs",
    jersey: "25",
  },
  {
    name: "Victor Wembanyama",
    img: "/plaers/Victor Wembanyama.avif",
    height: "7 ft 4 in",
    weight: "230 lbs",
    jersey: "1",
  },
  {
    name: "Scoot Henderson",
    img: "/players/Scoot Henderson.webp",
    height: "6 ft 2 in",
    weight: "195 lbs",
    jersey: "0",
  },
  {
    name: "Devin Vassell",
    img: "/players/Devin Vassell.avif",
    height: "6 ft 5 in",
    weight: "200 lbs",
    jersey: "24",
  },
  {
    name: "Keldon Johnson",
    img: "/players/Keldon Johnson.avif",
    height: "6 ft 6 in",
    weight: "220 lbs",
    jersey: "3",
  },
  {
    name: "Zach Collins",
    img: "/players/Zach Collins.avif",
    height: "6 ft 11 in",
    weight: "250 lbs",
    jersey: "23",
  },
  {
    name: "Fred VanVleet",
    img: "/players/Fred VanVleet.webp",
    height: "6 ft 1 in",
    weight: "197 lbs",
    jersey: "23",
  },
  {
    name: "Scottie Barnes",
    img: "/players/Scottie Barnes.webp",
    height: "6 ft 7 in",
    weight: "225 lbs",
    jersey: "4",
  },
  {
    name: "OG Anunoby",
    img: "/players/OG Anunoby.webp",
    height: "6 ft 7 in",
    weight: "232 lbs",
    jersey: "3",
  },
  {
    name: "Pascal Siakam",
    img: "/players/Pascal Siakam.webp",
    height: "6 ft 9 in",
    weight: "230 lbs",
    jersey: "43",
  },
  {
    name: "Jakob Poeltl",
    img: "/players/Jakob Poeltl.webp",
    height: "7 ft 1 in",
    weight: "245 lbs",
    jersey: "19",
  },
  {
    name: "Lauri Markkanen",
    img: "/players/Lauri Markkanen.avif",
    height: "7 ft 0 in",
    weight: "240 lbs",
    jersey: "23",
  },
  {
    name: "Collin Sexton",
    img: "/players/Collin Sexton.webp",
    height: "6 ft 1 in",
    weight: "190 lbs",
    jersey: "2",
  },
  {
    name: "Kris Dunn",
    img: "/players/Kris Dunn.png",
    height: "6 ft 3 in",
    weight: "205 lbs",
    jersey: "11",
  },
  {
    name: "Jarred Vanderbilt",
    img: "/players/Jarred Vanderbilt.avif",
    height: "6 ft 8 in",
    weight: "214 lbs",
    jersey: "2",
  },
  {
    name: "Walker Kessler",
    img: "/players/Walker Kessler.avif",
    height: "7 ft 1 in",
    weight: "245 lbs",
    jersey: "24",
  },
  {
    name: "Kyle Kuzma",
    img: "/players/Kyle Kuzma.webp",
    height: "6 ft 9 in",
    weight: "221 lbs",
    jersey: "33",
  },
  {
    name: "Corey Kispert",
    img: "/players/Corey Kispert.webp",
    height: "6 ft 7 in",
    weight: "224 lbs",
    jersey: "24",
  },
  {
    name: "Kristaps Porziņģis",
    img: "/players/Kristaps Porziņģis.webp",
    height: "7 ft 3 in",
    weight: "240 lbs",
    jersey: "6",
  },
  {
    name: "Daniel Gafford",
    img: "/players/Daniel Gafford.avif",
    height: "6 ft 10 in",
    weight: "234 lbs",
    jersey: "21",
  },
  {
    name: "Delon Wright",
    img: "/players/Delon Wright.webp",
    height: "6 ft 5 in",
    weight: "185 lbs",
    jersey: "55",
  },
];
