/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type Match = {
  _id: string;
  _type: "match";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  firstTeam?: string;
  secondTeam?: string;
  firstTeamPlayers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "player";
  }>;
  secondTeamPlayers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "player";
  }>;
  score?: {
    firstTeamScore?: number;
    secondTeamScore?: number;
  };
  winner?: string;
};

export type Player = {
  _id: string;
  _type: "player";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  matchDays?: Array<{
    date?: string;
    fieldGoals?: {
      points_2?: Array<{
        value?: number;
        dot?: {
          x?: number;
          y?: number;
          made?: boolean;
        };
        _key: string;
      }>;
      points_3?: Array<{
        value?: number;
        dot?: {
          x?: number;
          y?: number;
          made?: boolean;
        };
        _key: string;
      }>;
      points_1?: Array<{
        value?: number;
        dot?: {
          x?: number;
          y?: number;
          made?: boolean;
        };
        _key: string;
      }>;
    };
    fouls?: Array<{
      value?: number;
      dot?: {
        x?: number;
        y?: number;
        made?: boolean;
      };
      _key: string;
    }>;
    oRebounds?: Array<{
      value?: number;
      dot?: {
        x?: number;
        y?: number;
        made?: boolean;
      };
      _key: string;
    }>;
    dRebounds?: Array<{
      value?: number;
      dot?: {
        x?: number;
        y?: number;
        made?: boolean;
      };
      _key: string;
    }>;
    steals?: Array<{
      value?: number;
      dot?: {
        x?: number;
        y?: number;
      };
      _key: string;
    }>;
    assists?: Array<{
      value?: number;
      dot?: {
        x?: number;
        y?: number;
      };
      _key: string;
    }>;
    blocks?: Array<{
      value?: number;
      dot?: {
        x?: number;
        y?: number;
      };
      _key: string;
    }>;
    missedShots?: Array<{
      value?: number;
      dot?: {
        x?: number;
        y?: number;
      };
      _key: string;
    }>;
    _key: string;
  }>;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData | Match | Player;
export declare const internalGroqTypeReferenceTo: unique symbol;
